# Generated by Django 3.2.9 on 2022-03-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='published',
        ),
    ]
