# Generated by Django 3.2.9 on 2022-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_remove_genre_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='poster',
            field=models.ImageField(default='GenrePosters/default.jpg', upload_to='GenrePosters/'),
        ),
    ]
