# Generated by Django 3.2.9 on 2022-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('thumbnail', models.ImageField(default='SongsThumbnails/default.jpg', upload_to='SongsThumbnails/')),
                ('song', models.FileField(blank=True, null=True, upload_to='Songs/')),
                ('song_url', models.CharField(blank=True, max_length=350, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('single_track', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Music',
            },
        ),
    ]
