# Generated by Django 3.2.9 on 2022-03-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('genre', '0001_initial'),
        ('artist', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
        migrations.AddField(
            model_name='music',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ManyToManyField(to='genre.Genre'),
        ),
    ]
