# Generated by Django 3.2.9 on 2022-03-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='genre',
            new_name='genres',
        ),
    ]
