# Generated by Django 3.2.9 on 2022-03-19 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_rename_genre_music_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='song_url',
        ),
        migrations.AddField(
            model_name='music',
            name='page_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='song_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MusicComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.comment')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.comment',),
        ),
    ]
