# Generated by Django 3.2.9 on 2022-03-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='song_url',
            new_name='song_online_url',
        ),
    ]
