# Generated by Django 3.2.9 on 2022-03-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_song_url_music_song_online_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='song_online_url',
        ),
    ]
