# Generated by Django 3.2.9 on 2022-03-18 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_music_page_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.comment')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.comment',),
        ),
    ]
