# Generated by Django 3.2.9 on 2022-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageposter',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepageposter',
            name='url_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
