# Generated by Django 3.2.9 on 2022-03-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220315_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageposter',
            old_name='url',
            new_name='albums_url',
        ),
    ]
