# Generated by Django 3.2.9 on 2022-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_published'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
    ]
