# Generated by Django 3.2.9 on 2022-03-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_published'),
        ('core', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_download_link_high_file',
            field=models.FileField(blank=True, null=True, upload_to='AlbumsZipHigh/'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_download_link_medium_file',
            field=models.FileField(blank=True, null=True, upload_to='AlbumsZipMedium/'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist'),
        ),
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.comment')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.comment',),
        ),
    ]
