# Generated by Django 3.2.9 on 2022-03-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_download_link_high_file',
            field=models.FileField(blank=True, null=True, upload_to='AlbumsZipHigh/'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_download_link_medium_file',
            field=models.FileField(blank=True, null=True, upload_to='AlbumsZipMedium/'),
        ),
    ]
